spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bussiness?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wyf19980715
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect


